version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FINANCE_SERVICE_URL=http://financeservice:8000
      - ESG_SERVICE_URL=http://esgservice:8002
      - STOCK_SERVICE_URL=http://stockservice:8001
    volumes:
      - ./gateway:/app
    networks:
      - lif-network
    depends_on:
      - financeservice
      - esgservice
      - stockservice
    
  financeservice:
    build:
      context: ./financeservice
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/lifdb
    volumes:
      - ./financeservice:/app
    networks:
      - lif-network
    depends_on:
      - postgres
    
  esgservice:
    build:
      context: ./esgservice
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/lifdb
    volumes:
      - ./esgservice:/app
    networks:
      - lif-network
    depends_on:
      - postgres
    
  stockservice:
    build:
      context: ./stockservice
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/lifdb
    volumes:
      - ./stockservice:/app
    networks:
      - lif-network
    depends_on:
      - postgres
    
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lifdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lif-network

networks:
  lif-network:
    driver: bridge

volumes:
  postgres_data: 